// tabs actions
export const ADD_TAB = "ADD_TAB";
export const COPY_TAB = "COPY_TAB";
export const DELETE_TAB = "DELETE_TAB";
export const CHANGE_TAB = "CHANGE_TAB";
export const RESET_TAB = "RESET_TAB";

// hero actions
export const CHANGE_HERO = "CHANGE_HERO";
export const CHANGE_STATS = "CHANGE_STATS";
export const CHANGE_WEAPON = "CHANGE_WEAPON";
export const CHANGE_REFINE = "CHANGE_REFINE";
export const CHANGE_ASSIST = "CHANGE_ASSIST";
export const CHANGE_SPECIAL = "CHANGE_SPECIAL";
export const CHANGE_ASLOT = "CHANGE_ASLOT";
export const CHANGE_BSLOT = "CHANGE_BSLOT";
export const CHANGE_CSLOT = "CHANGE_CSLOT";
export const CHANGE_SSLOT = "CHANGE_SSLOT";
export const CHANGE_LEVELS = "CHANGE_LEVELS";
export const CHANGE_MERGES = "CHANGE_MERGES";
export const CHANGE_DRAGONFLOWERS = "CHANGE_DRAGONFLOWERS";
export const CHANGE_RESPLENDENT = "CHANGE_RESPLENDENT";
export const CHANGE_RESPLENDENT_STATS = "CHANGE_RESPLENDENT_STATS";
export const CHANGE_TRANSFORMED = "CHANGE_TRANSFORMED";
export const CHANGE_BLESSING = "CHANGE_BLESSING";
export const CHANGE_BLESSING_STATS = "CHANGE_BLESSING_STATS";
export const CHANGE_SUMMONER_SUPPORT = "CHANGE_SUMMONER_SUPPORT";
export const CHANGE_ALLY_SUPPORT = "CHANGE_ALLY_SUPPORT";
export const CHANGE_BACKGROUND = "CHANGE_BACKGROUND";
export const CHANGE_FAVORITE = "CHANGE_FAVORITE";

export const COPY_HERO = "COPY_HERO";

// display actions
export const CHANGE_NAME_DISPLAY = "CHANGE_NAME_DISPLAY";
export const CHANGE_GRIMA = "CHANGE_GRIMA";
export const CHANGE_BACKPACK = "CHANGE_BACKPACK";
export const CHANGE_DUO_DISPLAY = "CHANGE_DUO_DISPLAY";
export const CHANGE_TAB_IMAGE_DISPLAY = "CHANGE_TAB_IMAGE_DISPLAY";

// barracks actions
export const SAVE_BUILD_TO_BARRACKS = "SAVE_BUILD_TO_BARRACKS";
export const LOAD_BUILD_FROM_BARRACKS = "LOAD_BUILD_FROM_BARRACKS";
export const DELETE_BUILD_FROM_BARRACKS = "DELETE_BUILD_FROM_BARRACKS";
